<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="15.1.3" />
		<PackageReference Include="CloudinaryDotNet" Version="1.29.2" />
		<PackageReference Include="ErrorOr" Version="2.1.1" />
		<PackageReference Include="FluentValidation" Version="12.1.1" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
		<PackageReference Include="Google.Apis.Auth" Version="1.75.0" />
		<PackageReference Include="MediatR" Version="12.5.0" />
		<PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.11" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
	</ItemGroup>

  <ItemGroup>
    <Folder Include="Common\Helpers\" />
    <Folder Include="Features\Auth\Specifications\" />
    <Folder Include="Features\Users\Commands\" />
  </ItemGroup>

</Project>
